language: shell
install: true

matrix:
  include:
    - name: "clang on macOS"
      os: osx
      osx_image: xcode11
      env:
        - CC=clang
        - CXX=clang++
      install:
        - ${CC} --version
        - ${CXX} --version
      script:
        # build & test
        - echo Starting Build...
        - pushd code
        - bash build.sh
        - popd
